version: '3.8'
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    command: npx nodemon --inspect=0.0.0.0:9229 index.js -- -h 0.0.0.0 -p 8800 -c ./cache
    ports:
      - "8800:8800"
      - "9229:9229"
    volumes:
      - ./cache:/usr/src/app/cache
